# Week 1: Python and Colab Foundations
**CERT x492 · Data Analytics Programming**

Use this notebook to practice Python calculations, explore a small table of daily bike rentals, and check an AI-assisted correction. Save your own copy as **`bike_sharing_analysis.ipynb`**; you will build on this notebook during the course.

**Work one code cell at a time on your first pass.** Part 4 contains one intentional coding error. Correct it before the final clean-session run.

The seven sample records are included in the notebook. You can begin without downloading or uploading a CSV. The separate sample CSV contains the same records for reference.

**Your name:** Brady

## What you will submit
Submit **one GitHub repository link in Canvas**. Your repository must contain your completed `bike_sharing_analysis.ipynb` with outputs and a `README.md`. This single submission covers **Activity 1 and Project Part 1**.

## How to use this notebook
- **Read:** Review the explanation; no written response is required.
- **Run this example — no edits needed:** Run the next code cell and keep its output visible.
- **Your turn — Code:** Edit and run the designated code cell.
- **Your turn — Explain:** Write in the separate **Student response** cell directly below the questions. Use 1–2 sentences per question.

Keep the supplied instructions and examples. Replace response placeholders with your own answers. Complete every **Your turn** task.

## Goal
By the end of this activity, you will have Python practice code, a daily casual-rental percentage, a simple sample summary, brief explanations, and a verified coding correction in one notebook.

The course project will ask: **How do daily rental volumes vary with calendar and weather conditions, and what limitations should an operations manager consider when interpreting those patterns?** Use this small sample for Week 1 practice. You will work with the full daily file in Week 2.


**Read:** No written response is required in this section.

## Part 1: Colab setup
1. Upload this `.ipynb` file into [Google Colab](https://colab.research.google.com/), or open the instructor's shared copy when available.
2. Save your own copy in Google Drive and rename it `bike_sharing_analysis.ipynb`.
3. To run a code cell, select its play button or press **Shift + Enter**. Wait for it to finish before moving on.
4. Double-click a text cell to edit your explanations. Code cells run Python; text cells hold instructions and written responses.

Run the setup cell below. `pandas` is the library we will use for tables; `pd` is its short name in this notebook. Colab's standard Python runtime is sufficient for this activity.


**Run this example — no edits needed:** Run the next code cell and keep its output visible.

In [ ]:
import pandas as pd

print("Notebook ready. Continue to Python foundations.")

Notebook ready. Continue to Python foundations.

## Part 2: Python foundations
### Variables and data types
A variable gives a name to a value. Run the example, then read the printed value types:

- `str`: text.
- `int`: a whole number.
- `float`: a decimal number.

The rental counts below come from January 1, 2011. `fraction_example` is a separate practice value.


**Run this example — no edits needed:** Run the next code cell and keep its output visible.

In [ ]:
sample_date = "2011-01-01"
casual_rentals = 331
registered_rentals = 654
fraction_example = 0.25

print("Date:", sample_date, type(sample_date))
print("Casual rentals:", casual_rentals, type(casual_rentals))
print("Registered rentals:", registered_rentals, type(registered_rentals))
print("Practice fraction:", fraction_example, type(fraction_example))

Date: 2011-01-01 <class 'str'>
Casual rentals: 331 <class 'int'>
Registered rentals: 654 <class 'int'>
Practice fraction: 0.25 <class 'float'>

### Calculate a total and a percentage
`+` adds values, `/` divides, and `*` multiplies. `print()` shows a result. `round(value, 2)` displays a number rounded to two decimal places.

Before running the next cell, predict the total rentals. Then run it and examine the percentage.


**Run this example — no edits needed:** Run the next code cell and keep its output visible.

In [ ]:
total_rentals = casual_rentals + registered_rentals
casual_percent = casual_rentals / total_rentals * 100

print("Total rentals:", total_rentals)
print("Casual rental percentage:", round(casual_percent, 2), "%")

Total rentals: 985
Casual rental percentage: 33.6 %

### Change a value
Run the practice cell once as supplied. Then change `practice_casual` from **331 to 400** and run the entire cell again. The registered-rental value stays at 654.

These are practice variables. Changing them leaves the source records in Part 3 unchanged.

**Your turn — Code:** Edit and run the next cell. Leave `practice_casual = 400` in your submitted notebook and keep its resulting output visible.

In [ ]:
practice_casual = 400  # Change this to 400 and run the cell again.
practice_registered = 654
practice_total = practice_casual + practice_registered
practice_percent = practice_casual / practice_total * 100

print("Practice total rentals:", practice_total)
print("Practice casual percentage:", round(practice_percent, 2), "%")

Practice total rentals: 1054
Practice casual percentage: 37.95 %

### Your turn — Explain: Python practice
Write 1–2 sentences per question in the Student response cell below.

1. What does the January 1 casual rental percentage from the original example mean?
2. After changing `practice_casual` to 400, how did the total rentals and casual rental percentage change compared with the original example? Include the new values.
3. Which variable contains text, which contains a whole number, and which contains a decimal number? Give one example of each from the variables-and-data-types code cell.

**Student response — Python practice**

1. Your answer:

2. Your answer:

3. Your answer:

## Part 3: Explore the sample DataFrame
A **DataFrame** is a table with rows and columns. Each row here describes one day.

| Column | Meaning |
| --- | --- |
| `dteday` | Date, kept as text for this activity. |
| `casual` | Number of rentals by casual users that day. |
| `registered` | Number of rentals by registered users that day. |
| `cnt` | Total rentals that day: casual plus registered. |

These are counts of rentals; a rental count does not establish a count of distinct people.

Run the supplied data block as it is. It places the seven daily records into a DataFrame named `bike_rentals`. Keep the source values unchanged.


**Run this example — no edits needed:** Run the next code cell and keep its output visible.

In [ ]:
sample_data = {
    'dteday': ['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04', '2011-01-05', '2011-01-06', '2011-01-07'],
    'casual': [331, 131, 120, 108, 82, 88, 148],
    'registered': [654, 670, 1229, 1454, 1518, 1518, 1362],
    'cnt': [985, 801, 1349, 1562, 1600, 1606, 1510],
}

bike_rentals = pd.DataFrame(sample_data)
bike_rentals

       dteday  casual  registered   cnt
0  2011-01-01     331         654   985
1  2011-01-02     131         670   801
2  2011-01-03     120        1229  1349
3  2011-01-04     108        1454  1562
4  2011-01-05      82        1518  1600
5  2011-01-06      88        1518  1606
6  2011-01-07     148        1362  1510

### Inspect rows and columns
`bike_rentals.shape` describes the table's dimensions. The first number is the row count; the second is the column count. In Python, positions begin at zero, so `[0]` selects the first number and `[1]` selects the second.

Run this cell before adding your new percentage column.


**Run this example — no edits needed:** Run the next code cell and keep its output visible.

In [ ]:
print("Rows:", bike_rentals.shape[0])
print("Columns:", bike_rentals.shape[1])

Rows: 7
Columns: 4

### Select a column
Use the table name followed by a column name in square brackets. Column names must match exactly, including spelling and capitalization. Run this example to see the seven casual-rental counts.


**Run this example — no edits needed:** Run the next code cell and keep its output visible.

In [ ]:
bike_rentals["casual"]

0    331
1    131
2    120
3    108
4     82
5     88
6    148
Name: casual, dtype: int64

### Your turn — Code: calculate the casual rental percentage
Add a line of code to the next cell that creates a new column named `casual_pct`.

Use the same percentage calculation as in Part 2, now applied to two table columns:

**casual rental percentage = casual rentals / total rentals × 100**

Use `bike_rentals["casual"]` for casual rentals and `bike_rentals["cnt"]` for total rentals. Assign the calculation to `bike_rentals["casual_pct"]` using `=`.

Leave `bike_rentals` as the final line to display the completed table. Every total in this sample is greater than zero.

In [ ]:
# Add your casual_pct calculation here.

bike_rentals

       dteday  casual  registered   cnt  casual_pct
0  2011-01-01     331         654   985   33.604061
1  2011-01-02     131         670   801   16.354557
2  2011-01-03     120        1229  1349    8.895478
3  2011-01-04     108        1454  1562    6.914213
4  2011-01-05      82        1518  1600    5.125000
5  2011-01-06      88        1518  1606    5.479452
6  2011-01-07     148        1362  1510    9.801325

### Summarize the sample
`len(bike_rentals)` gives the number of rows. Each row is one day. `.sum()` adds the values in a selected column.

Run the summary and explain what its total represents.


**Run this example — no edits needed:** Run the next code cell and keep its output visible.

In [ ]:
sample_days = len(bike_rentals)
sample_total_rentals = bike_rentals["cnt"].sum()

print("Days in the sample:", sample_days)
print("Total rentals in the sample:", sample_total_rentals)

### Your turn — Explain: the sample
Write 1–2 sentences per question in the Student response cell below.

1. How many rows and original columns were in the sample before adding `casual_pct`? What does one row represent?
2. Which two rental categories are included in `cnt`?
3. How many days are included in the sample, and how many rentals occurred across those days?

Keep your answers specific to January 1–7, 2011.

**Student response — Sample exploration**

1. Your answer:

2. Your answer:

3. Your answer:

## Part 4: AI-assisted troubleshooting
The next exercise repeats the Part 3 percentage calculation with an intentional error so you can practice troubleshooting. Correcting it should reproduce your Part 3 results.

**Your turn — Code: This next cell has one intentional error.** Run it, read the error message, and use an AI tool of your choice to help explain the problem and suggest a correction.

You can ask: "I am learning pandas. This code should calculate the percentage of daily rentals made by casual users. Explain the error and suggest a correction using only the columns available in my table."

Provide the faulty code, the error message, and the column names shown in Part 3. Use the public course data and protect personal, workplace, and confidential information.

Review the suggestion, then **edit this same code cell** to apply the correction. After the correction, rerun it and complete the independent check below.

Record your explanation in the Student response cell below the independent check. No screenshots or AI conversation transcript are required.

In [ ]:
bike_rentals["casual_pct"] = bike_rentals["casual"] / bike_rentals["cnt"] * 100
bike_rentals

       dteday  casual  registered   cnt  casual_pct
0  2011-01-01     331         654   985   33.604061
1  2011-01-02     131         670   801   16.354557
2  2011-01-03     120        1229  1349    8.895478
3  2011-01-04     108        1454  1562    6.914213
4  2011-01-05      82        1518  1600    5.125000
5  2011-01-06      88        1518  1606    5.479452
6  2011-01-07     148        1362  1510    9.801325

## Checks
### Verify the corrected result independently
Using a calculator, compute **131 / 801 × 100** for January 2, 2011. Record the result in the Student response cell under “AI correction and verification.” Then run the next cell and compare your calculator result with the January 2 row.

Checking that code runs is one step. Comparing its output with a separately checked calculation establishes whether it gives the intended result.


**Run this example — no edits needed:** Run the next code cell and keep its output visible.

In [ ]:
bike_rentals[["dteday", "casual", "cnt", "casual_pct"]]

       dteday  casual   cnt  casual_pct
0  2011-01-01     331   985   33.604061
1  2011-01-02     131   801   16.354557
2  2011-01-03     120  1349    8.895478
3  2011-01-04     108  1562    6.914213
4  2011-01-05      82  1600    5.125000
5  2011-01-06      88  1606    5.479452
6  2011-01-07     148  1510    9.801325

### Your turn — Explain: AI correction and verification
Answer each prompt in the Student response cell below. Use 1–2 sentences per prompt.

1. Name the AI tool you actually used.
2. Identify the incorrect column name and explain why it caused an error.
3. Describe the correction you applied.
4. Report your calculator result for January 2 (`131 / 801 × 100`), rounded to two decimal places. Does it match the corrected table when rounded to the same precision? What does that percentage mean for that day?

**Student response — AI correction and verification**

1. AI tool used:

2. Coding problem:

3. Correction:

4. Calculator result, comparison, and meaning:

### Check a clean session
Restarting clears stored variables. This check confirms that the notebook works from the beginning without depending on earlier runs.

Complete the practice changes, new-column calculation, AI correction, and written responses first. Save your notebook.

1. Select **Runtime → Disconnect and delete runtime** in Colab.
2. Reconnect and run all code cells from the first cell to the last.
3. Check that the sample table and results are recreated without errors.
4. Save the notebook with the recreated outputs.
5. Answer the question in the Student response cell below.

**Your turn — Explain:** Did every code cell run from top to bottom without errors? If you fixed anything during this check, briefly describe it. Use 1–2 sentences.

Need help? Contact your instructor or bring your questions to the optional weekly Zoom session.

**Student response — Clean-session confirmation**

Your answer:

## Submission checklist: Activity 1 and Project Part 1
Submit **one GitHub repository link in Canvas**. This covers both Activity 1 and Project Part 1.

Before submitting, confirm that:
- [ ] Your notebook is named `bike_sharing_analysis.ipynb`.
- [ ] The practice cell uses `practice_casual = 400` and shows its output.
- [ ] You completed the `casual_pct` calculation and retained the sample summary output.
- [ ] You corrected the intentional error in the original faulty code cell.
- [ ] Every Student response cell contains your answers, including the AI tool used and independent calculator check.
- [ ] All code cells run from top to bottom without errors in a clean session, and you recorded the confirmation.
- [ ] You saved the notebook with its outputs, downloaded the `.ipynb` file, and uploaded it to your GitHub repository through the browser.
- [ ] Your repository contains a `README.md` using the copy-ready text below.
- [ ] Your instructor can access the repository. For a private repository, use the instructor username provided in the course to invite the instructor as a collaborator and confirm the invitation has been accepted.
- [ ] You submitted the repository link in Canvas.

[Create a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/quickstart-for-repositories) · [Upload the notebook through the browser](https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository)

### Copy this text into your GitHub README
Copy the text between the **Start of README text** and **End of README text** markers into your repository's `README.md`. The text is complete; no responses are required in this section.

**Start of README text**


**Business question:** How do daily rental volumes vary with calendar and weather conditions, and what limitations should an operations manager consider when interpreting those patterns?

**Data source:** [UCI Bike Sharing dataset](https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset). Week 1 uses the January 1–7, 2011 sample included in the notebook; later modules use the full daily file.

**Notebook purpose:** This notebook practices basic Python calculations, explores seven days of bike rental data, calculates casual rental percentages, and documents an AI-assisted code correction checked with a calculator.

**Data attribution:**
Fanaee-T, H. (2013). *Bike Sharing* [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C5W894. Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

Week 1 adaptation: the first seven daily records (January 1–7, 2011), with four original columns selected. Original dates and rental counts are unchanged. The `casual_pct` column is calculated during the activity.

**End of README text**

## Data source and attribution
Fanaee-T, H. (2013). *Bike Sharing* [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C5W894. Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

Week 1 adaptation: the first seven daily records (January 1–7, 2011), with four original columns selected. Original dates and rental counts are unchanged. The `casual_pct` column is calculated during the activity.

[Official dataset](https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset) · [Public file mirror used for this draft](https://github.com/udacity/deep-learning-v2-pytorch/blob/master/project-bikesharing/Bike-Sharing-Dataset/day.csv)

These records were extracted from the linked public mirror of the UCI daily file. Dates and rental counts were retained. The notebook's embedded data and the separate sample CSV contain the same seven records.


**Read:** No written response is required in this section.